project:
  title: "SunQuarTeX"
  output-dir: _output

profile: 
  group: 
    - [cn, en]
    - [art, pre]
    - [cnart, enart, cnpre, enpre]

# --- article ---

number-sections: true
number-depth: 3

cap-location: bottom
fig-align: center

jupyter: python3