toc: true

format:
  revealjs: default
  beamer:
    pdf-engine: xelatex
    theme: madrid
    cite-method: biblatex # override the default csl cite method
    execute:
      echo: false
    fig-pos: H
  pptx: default