csl: "./_assets/china-national-standard-gb-t-7714-2015-numeric-comma-names-delimiter.csl"

crossref: 
  tbl-prefix: "表"
  tbl-title: "表"
  fig-prefix: "图"
  fig-title: "图"
  eq-prefix: "式"
  eq-title: "式"
  sec-prefix: "小节"
  thm-prefix: "定理"
  thm-title: "定理"
  lem-prefix: "引理"
  lem-title: "引理"
  cor-prefix: "推论"
  cor-title: "推论"
  prp-prefix: "命题"
  prp-title: "命题"
  cnj-prefix: "猜想"
  cnj-title: "猜想"
  def-prefix: "定义"
  def-title: "定义"
  exm-prefix: "例"
  exm-title: "例"
  exr-prefix: "习题"
  exr-title: "习题"