toc: true
# slide-level: # left default to handle automatically, see Pandoc manual
format:
  revealjs: default
  beamer:
    pdf-engine: xelatex
    theme: madrid
    cite-method: biblatex # override the default csl cite method
    execute:
      echo: false
    fig-pos: false
  pptx: default